version: '3.9'

services:
  postgres:
    # image: postgres:15-alpine
    image: pgvector/pgvector:pg16
    restart: unless-stopped    
    ports:
      - 5432:5432
    volumes:
      - multisql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rag
      - POSTGRES_USER=rag
      - POSTGRES_PASSWORD=rag

volumes:
  multisql:
    driver: local
